spring:
  config:
    activate:
      on-profile: local
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dem_storage
    username: root
    password: password
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dem-mysql:3306/dem_storage
    username: root
    password: password
server:
  port: 8080