[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
p2p = { path = "../p2p" }
tokio = { workspace = true }
prost = "0.12.6"
tonic = "0.10.2"
prost-types = "0.12.6"
proto = { path = "../proto" }