[workspace]
resolver = "2"
members = [
    "crypto",
    "node",
    "p2p",
    "proto"
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
