[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = { version = "0.10.2", features = ["rustls"]}
rustls = { version = "0.21.0", features = ["quic", "dangerous_configuration"] }
eyre = "0.6.12"
rcgen = "0.12.1"
tokio = { version = "1.37.0", features = ["full"] }